import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { describe, it } from 'node:test';
import {
  minimumNativeVersion,
  nativeFingerprint,
  nativePluginsOf,
} from '../lib/native-fingerprint.mjs';

// capacitor.settings.gradle as `cap sync` writes it.
const includeOf = (name, path) =>
  `include ':${name}'\nproject(':${name}').projectDir = new File('../node_modules/${path}')\n`;
const SETTINGS = [
  '// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN',
  includeOf('capacitor-android', '@capacitor/android/capacitor'),
  includeOf('capawesome-capacitor-live-update', '@capawesome/capacitor-live-update/android'),
  includeOf('capacitor-app', '@capacitor/app/android'),
].join('\n');
const TRACKED = [
  '100644 1111111111111111111111111111111111111111 0\tsrc/LoDb.Web/android/app/build.gradle',
  '100755 2222222222222222222222222222222222222222 0\tsrc/LoDb.Web/android/gradlew',
].join('\n');
const LOCK = {
  packages: {
    'node_modules/@capacitor/android': { version: '8.5.2' },
    'node_modules/@capacitor/app': { version: '8.1.1' },
    'node_modules/@capawesome/capacitor-live-update': { version: '8.4.4' },
  },
};
const PLUGINS = nativePluginsOf(SETTINGS);
const FINGERPRINT = nativeFingerprint({ trackedFiles: TRACKED, plugins: PLUGINS, lock: LOCK });

describe('nativePluginsOf', () => {
  it('lists the packages that cap sync included in Gradle', () => {
    assert.deepEqual(PLUGINS, [
      '@capacitor/android',
      '@capacitor/app',
      '@capawesome/capacitor-live-update',
    ]);
  });
});

describe('nativeFingerprint', () => {
  const variant = (change) =>
    nativeFingerprint({ trackedFiles: TRACKED, plugins: PLUGINS, lock: LOCK, ...change });

  it('is stable whatever the order of the listing', () => {
    const reversed = TRACKED.split('\n').reverse().join('\n');

    assert.equal(variant({ trackedFiles: `${reversed}\n` }), FINGERPRINT);
  });

  it('changes with a file of the Android project', () => {
    assert.notEqual(variant({ trackedFiles: TRACKED.replace('1111', '1112') }), FINGERPRINT);
  });

  it('changes with a new native plugin', () => {
    const lock = {
      packages: { ...LOCK.packages, 'node_modules/@capacitor/share': { version: '8.0.2' } },
    };

    assert.notEqual(variant({ plugins: [...PLUGINS, '@capacitor/share'], lock }), FINGERPRINT);
  });

  it('changes with the version of a plugin', () => {
    const lock = structuredClone(LOCK);
    lock.packages['node_modules/@capacitor/app'].version = '8.2.0';

    assert.notEqual(variant({ lock }), FINGERPRINT);
  });

  it('refuses a plugin package-lock.json does not know', () => {
    assert.throws(() => variant({ plugins: ['@capacitor/camera'] }), /@capacitor\/camera/);
  });
});

describe('minimumNativeVersion', () => {
  const baseline = { minimumNativeVersion: '2.3.0', fingerprint: FINGERPRINT };

  it('keeps the minimum of the baseline while the native layer is the same', () => {
    assert.equal(
      minimumNativeVersion({ baseline, fingerprint: FINGERPRINT, version: '2.4.0' }),
      '2.3.0',
    );
  });

  it('stops the release whose native layer changed', () => {
    assert.throws(
      () => minimumNativeVersion({ baseline, fingerprint: 'f'.repeat(64), version: '2.4.0' }),
      /--update 2\.4\.0/,
    );
  });

  it('refuses a minimum above the release', () => {
    assert.throws(
      () => minimumNativeVersion({ baseline, fingerprint: FINGERPRINT, version: '2.2.0' }),
      /above the release/,
    );
  });

  it('reads a well formed committed baseline', () => {
    const committed = JSON.parse(
      readFileSync(new URL('../native-baseline.json', import.meta.url), 'utf8'),
    );

    assert.match(committed.minimumNativeVersion, /^\d+\.\d+\.\d+$/);
    assert.match(committed.fingerprint, /^[0-9a-f]{64}$/);
  });
});
