CREATE TABLE public.api_keys (
    id integer NOT NULL,
    name character varying(64) NOT NULL,
    key_hash character varying(64) NOT NULL,
    key_prefix character varying(12) NOT NULL,
    plan character varying(16) DEFAULT 'free'::character varying NOT NULL,
    monthly_quota integer DEFAULT 500 NOT NULL,
    credits_balance bigint DEFAULT 0 NOT NULL,
    rate_limit_per_min integer DEFAULT 10 NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp(0) with time zone NOT NULL,
    revoked_at timestamp(0) with time zone DEFAULT NULL::timestamp with time zone,
    stripe_customer_id character varying(64) DEFAULT NULL::character varying,
    stripe_subscription_id character varying(64) DEFAULT NULL::character varying,
    user_id integer NOT NULL
);
ALTER TABLE public.api_keys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_keys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.api_usage (
    id bigint NOT NULL,
    day date NOT NULL,
    requests bigint DEFAULT 0 NOT NULL,
    api_key_id integer NOT NULL
);
ALTER TABLE public.api_usage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_usage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.build_votes (
    id integer NOT NULL,
    value smallint NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    build_id integer NOT NULL,
    voter_id integer NOT NULL
);
ALTER TABLE public.build_votes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.build_votes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.builds (
    id integer NOT NULL,
    name character varying(80) NOT NULL,
    champion_id character varying(64) NOT NULL,
    game_version character varying(24) NOT NULL,
    description text,
    runes jsonb NOT NULL,
    steps jsonb NOT NULL,
    is_public boolean DEFAULT false NOT NULL,
    share_token character varying(24) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    owner_id integer NOT NULL,
    game_mode character varying(16) DEFAULT 'sr'::character varying NOT NULL,
    language character varying(8) DEFAULT 'en_US'::character varying NOT NULL
);
ALTER TABLE public.builds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.builds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.contact_messages (
    id integer NOT NULL,
    category character varying(255) NOT NULL,
    name character varying(120) DEFAULT NULL::character varying,
    email character varying(255) NOT NULL,
    subject character varying(160) DEFAULT NULL::character varying,
    message text NOT NULL,
    locale character varying(16) DEFAULT NULL::character varying,
    ip character varying(64) DEFAULT NULL::character varying,
    status character varying(255) DEFAULT 'new'::character varying NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    handled_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    user_id integer
);
ALTER TABLE public.contact_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);
CREATE TABLE public.donations (
    id integer NOT NULL,
    stripe_session_id character varying(255) NOT NULL,
    amount_cents integer NOT NULL,
    currency character varying(3) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    user_id integer
);
ALTER TABLE public.donations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.donations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.messenger_messages (
    id bigint NOT NULL,
    body text NOT NULL,
    headers text NOT NULL,
    queue_name character varying(190) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    available_at timestamp(0) without time zone NOT NULL,
    delivered_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);
ALTER TABLE public.messenger_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messenger_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.reset_password_request (
    id integer NOT NULL,
    selector character varying(20) NOT NULL,
    hashed_token character varying(100) NOT NULL,
    requested_at timestamp(0) without time zone NOT NULL,
    expires_at timestamp(0) without time zone NOT NULL,
    user_id integer NOT NULL
);
ALTER TABLE public.reset_password_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reset_password_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.users (
    id integer NOT NULL,
    email character varying(180) NOT NULL,
    username character varying(24) NOT NULL,
    roles json NOT NULL,
    password character varying(255),
    is_public_profile boolean DEFAULT false NOT NULL,
    favorite_champion_id character varying(64) DEFAULT NULL::character varying,
    favorite_item_id character varying(16) DEFAULT NULL::character varying,
    favorite_rune_id character varying(16) DEFAULT NULL::character varying,
    favorite_summoner_id character varying(64) DEFAULT NULL::character varying,
    created_at timestamp(0) without time zone NOT NULL,
    google_id character varying(30) DEFAULT NULL::character varying,
    riot_tagline character varying(5) DEFAULT NULL::character varying,
    is_supporter boolean DEFAULT false NOT NULL,
    is_banned boolean DEFAULT false NOT NULL,
    banned_at timestamp(0) with time zone DEFAULT NULL::timestamp with time zone,
    ban_reason character varying(255) DEFAULT NULL::character varying,
    is_verified boolean DEFAULT false NOT NULL,
    favorite_skin_id character varying(64) DEFAULT NULL::character varying,
    preferred_version character varying(24) DEFAULT NULL::character varying
);
ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.api_usage
    ADD CONSTRAINT api_usage_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.build_votes
    ADD CONSTRAINT build_votes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.builds
    ADD CONSTRAINT builds_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.contact_messages
    ADD CONSTRAINT contact_messages_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);
ALTER TABLE ONLY public.donations
    ADD CONSTRAINT donations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.messenger_messages
    ADD CONSTRAINT messenger_messages_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.reset_password_request
    ADD CONSTRAINT reset_password_request_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
CREATE INDEX idx_11530dc417c13f8b ON public.build_votes USING btree (build_id);
CREATE INDEX idx_11530dc4ebb4b8ad ON public.build_votes USING btree (voter_id);
CREATE INDEX idx_412782017b00651c ON public.contact_messages USING btree (status);
CREATE INDEX idx_412782018b8e8428 ON public.contact_messages USING btree (created_at);
CREATE INDEX idx_41278201a76ed395 ON public.contact_messages USING btree (user_id);
CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON public.messenger_messages USING btree (queue_name, available_at, delivered_at, id);
CREATE INDEX idx_7ce748aa76ed395 ON public.reset_password_request USING btree (user_id);
CREATE INDEX idx_9579321fa76ed395 ON public.api_keys USING btree (user_id);
CREATE INDEX idx_ab264a57e3c61f9 ON public.builds USING btree (owner_id);
CREATE INDEX idx_cde98962a76ed395 ON public.donations USING btree (user_id);
CREATE INDEX idx_f47e0aa08be312b3 ON public.api_usage USING btree (api_key_id);
CREATE UNIQUE INDEX uniq_1483a5e976f5c865 ON public.users USING btree (google_id);
CREATE UNIQUE INDEX uniq_9579321f57bfb971 ON public.api_keys USING btree (key_hash);
CREATE UNIQUE INDEX uniq_ab264a5d6594dd6 ON public.builds USING btree (share_token);
CREATE UNIQUE INDEX uniq_api_usage_key_day ON public.api_usage USING btree (api_key_id, day);
CREATE UNIQUE INDEX uniq_build_votes_build_voter ON public.build_votes USING btree (build_id, voter_id);
CREATE UNIQUE INDEX uniq_cde989621a314a57 ON public.donations USING btree (stripe_session_id);
CREATE UNIQUE INDEX uniq_users_email_lower ON public.users USING btree (lower((email)::text));
CREATE UNIQUE INDEX uniq_users_username_lower ON public.users USING btree (lower((username)::text));
ALTER TABLE ONLY public.build_votes
    ADD CONSTRAINT fk_11530dc417c13f8b FOREIGN KEY (build_id) REFERENCES public.builds(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.build_votes
    ADD CONSTRAINT fk_11530dc4ebb4b8ad FOREIGN KEY (voter_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.contact_messages
    ADD CONSTRAINT fk_41278201a76ed395 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.reset_password_request
    ADD CONSTRAINT fk_7ce748aa76ed395 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT fk_9579321fa76ed395 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.builds
    ADD CONSTRAINT fk_ab264a57e3c61f9 FOREIGN KEY (owner_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.donations
    ADD CONSTRAINT fk_cde98962a76ed395 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.api_usage
    ADD CONSTRAINT fk_f47e0aa08be312b3 FOREIGN KEY (api_key_id) REFERENCES public.api_keys(id) ON DELETE CASCADE;
