# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    upload_manager.base_dir: '%kernel.project_dir%/public'
    
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
    App\Service\ClientManager:
        arguments:
            $defaultLocale: 'en_US'
            $appSecret: '%kernel.secret%'

    App\Service\SummonerManager:
        arguments:
            $baseDir: '%upload_manager.base_dir%'
    App\Service\Utils:
        arguments:
            $baseDir: '%upload_manager.base_dir%'
    App\Service\ItemManager:
        arguments:
            $baseDir: '%upload_manager.base_dir%'
    App\Service\RiotManager:
        arguments:
            $baseDir: '%upload_manager.base_dir%'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
