// <auto-generated />
using System;
using LoDb.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoDb.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LoDbDbContext))]
    [Migration("20260926091745_Lot4Accounts")]
    partial class Lot4Accounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Accounts.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_identity_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_identity_roles_normalized_name");

                    b.ToTable("identity_roles", (string)null);
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Accounts.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("access_failed_count");

                    b.Property<string>("BanReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ban_reason")
                        .HasDefaultValueSql("NULL");

                    b.Property<DateTimeOffset?>("BannedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("banned_at")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<string>("FavoriteChampionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("favorite_champion_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("FavoriteItemId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("favorite_item_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("FavoriteRuneId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("favorite_rune_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("FavoriteSkinId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("favorite_skin_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("FavoriteSummonerId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("favorite_summoner_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("google_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_banned");

                    b.Property<bool>("IsPublicProfile")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_public_profile");

                    b.Property<bool>("IsSupporter")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_supporter");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("normalized_email")
                        .HasComputedColumnSql("upper((email)::text)", true);

                    b.Property<string>("NormalizedUserName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("normalized_username")
                        .HasComputedColumnSql("upper((username)::text)", true);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("PreferredVersion")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("preferred_version")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("RiotTagline")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("riot_tagline")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("roles");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("uniq_1483a5e976f5c865");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .HasDatabaseName("ix_users_normalized_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Audit.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("actor");

                    b.Property<int?>("ActorId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_type");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip");

                    b.Property<string>("Meta")
                        .HasColumnType("jsonb")
                        .HasColumnName("meta");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<string>("Route")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("route");

                    b.Property<string>("Target")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("target");

                    b.Property<string>("TargetId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_log_occurred_at");

                    b.HasIndex("Action", "OccurredAt")
                        .HasDatabaseName("ix_audit_log_action");

                    b.HasIndex("ActorId", "OccurredAt")
                        .HasDatabaseName("ix_audit_log_actor");

                    b.ToTable("audit_log", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_log_actor_type", "actor_type IN ('user', 'admin', 'anonymous')");

                            t.HasCheckConstraint("ck_audit_log_outcome", "outcome IN ('success', 'failure', 'denied')");
                        });
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Billing.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountCents")
                        .HasColumnType("integer")
                        .HasColumnName("amount_cents");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("StripeSessionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_session_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("donations_pkey");

                    b.HasIndex("StripeSessionId")
                        .IsUnique()
                        .HasDatabaseName("uniq_cde989621a314a57");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_cde98962a76ed395");

                    b.ToTable("donations", (string)null);
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Builds.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChampionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("champion_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("sr")
                        .HasColumnName("game_mode");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("game_version");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_public");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("en_US")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("Runes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("runes");

                    b.Property<string>("ShareToken")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("share_token");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("steps");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("builds_pkey");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("idx_ab264a57e3c61f9");

                    b.HasIndex("ShareToken")
                        .IsUnique()
                        .HasDatabaseName("uniq_ab264a5d6594dd6");

                    b.ToTable("builds", (string)null);
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Builds.BuildVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildId")
                        .HasColumnType("integer")
                        .HasColumnName("build_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("Value")
                        .HasColumnType("smallint")
                        .HasColumnName("value");

                    b.Property<int>("VoterId")
                        .HasColumnType("integer")
                        .HasColumnName("voter_id");

                    b.HasKey("Id")
                        .HasName("build_votes_pkey");

                    b.HasIndex("BuildId")
                        .HasDatabaseName("idx_11530dc417c13f8b");

                    b.HasIndex("VoterId")
                        .HasDatabaseName("idx_11530dc4ebb4b8ad");

                    b.HasIndex("BuildId", "VoterId")
                        .IsUnique()
                        .HasDatabaseName("uniq_build_votes_build_voter");

                    b.ToTable("build_votes", (string)null);
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Contact.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("handled_at")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("new")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("subject")
                        .HasDefaultValueSql("NULL");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("contact_messages_pkey");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_412782018b8e8428");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_412782017b00651c");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_41278201a76ed395");

                    b.ToTable("contact_messages", (string)null);
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Ddragon.DdragonAsset", b =>
                {
                    b.Property<string>("Version")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version");

                    b.Property<string>("Type")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<string>("Key")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key");

                    b.Property<string>("Extension")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("extension");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Version", "Type", "Key")
                        .HasName("pk_ddragon_asset");

                    b.ToTable("ddragon_asset", null, t =>
                        {
                            t.HasCheckConstraint("ck_ddragon_asset_blob", "(status = 'present' AND sha256 IS NOT NULL AND extension IS NOT NULL) OR (status = 'absent' AND sha256 IS NULL AND extension IS NULL)");

                            t.HasCheckConstraint("ck_ddragon_asset_extension", "extension ~ '^[a-z0-9]{1,8}$'");

                            t.HasCheckConstraint("ck_ddragon_asset_sha256", "sha256 ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_ddragon_asset_status", "status IN ('present', 'absent')");
                        });
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Ddragon.DdragonVersion", b =>
                {
                    b.Property<string>("Version")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset?>("PromotedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("promoted_at");

                    b.Property<DateTimeOffset?>("ReadyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ready_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Version")
                        .HasName("pk_ddragon_version");

                    b.ToTable("ddragon_version", null, t =>
                        {
                            t.HasCheckConstraint("ck_ddragon_version_attempts", "attempts >= 0");

                            t.HasCheckConstraint("ck_ddragon_version_status", "status IN ('discovered', 'ingesting', 'ready', 'failed')");
                        });
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Outbox.EmailOutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_error_code");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("locale");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("model");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("recipient");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("template");

                    b.HasKey("Id")
                        .HasName("pk_email_outbox");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("ix_email_outbox_pending")
                        .HasFilter("status = 'pending'");

                    b.ToTable("email_outbox", null, t =>
                        {
                            t.HasCheckConstraint("ck_email_outbox_attempts", "attempts >= 0");

                            t.HasCheckConstraint("ck_email_outbox_status", "status IN ('pending', 'sent', 'dead')");
                        });
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.PublicApi.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreditsBalance")
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("credits_balance");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("key_prefix");

                    b.Property<int>("MonthlyQuota")
                        .HasColumnType("integer")
                        .HasDefaultValue(500)
                        .HasColumnName("monthly_quota");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("free")
                        .HasColumnName("plan");

                    b.Property<int>("RateLimitPerMin")
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("rate_limit_per_min");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("revoked_at")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stripe_customer_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stripe_subscription_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("api_keys_pkey");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("uniq_9579321f57bfb971");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_9579321fa76ed395");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.PublicApi.ApiUsage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ApiKeyId")
                        .HasColumnType("integer")
                        .HasColumnName("api_key_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<long>("Requests")
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("requests");

                    b.HasKey("Id")
                        .HasName("api_usage_pkey");

                    b.HasIndex("ApiKeyId")
                        .HasDatabaseName("idx_f47e0aa08be312b3");

                    b.HasIndex("ApiKeyId", "Day")
                        .IsUnique()
                        .HasDatabaseName("uniq_api_usage_key_day");

                    b.ToTable("api_usage", (string)null);
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Scheduling.PeriodicJobState", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("LastStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_started_at");

                    b.Property<DateTimeOffset?>("LastSucceededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_succeeded_at");

                    b.HasKey("Name")
                        .HasName("pk_periodic_job");

                    b.ToTable("periodic_job", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_identity_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_identity_user_roles_role_id");

                    b.ToTable("identity_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_identity_user_tokens");

                    b.ToTable("identity_user_tokens", (string)null);
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Billing.Donation", b =>
                {
                    b.HasOne("LoDb.Infrastructure.Persistence.Accounts.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cde98962a76ed395");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Builds.Build", b =>
                {
                    b.HasOne("LoDb.Infrastructure.Persistence.Accounts.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ab264a57e3c61f9");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Builds.BuildVote", b =>
                {
                    b.HasOne("LoDb.Infrastructure.Persistence.Builds.Build", "Build")
                        .WithMany()
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_11530dc417c13f8b");

                    b.HasOne("LoDb.Infrastructure.Persistence.Accounts.User", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_11530dc4ebb4b8ad");

                    b.Navigation("Build");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Contact.ContactMessage", b =>
                {
                    b.HasOne("LoDb.Infrastructure.Persistence.Accounts.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_41278201a76ed395");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.PublicApi.ApiKey", b =>
                {
                    b.HasOne("LoDb.Infrastructure.Persistence.Accounts.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_9579321fa76ed395");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.PublicApi.ApiUsage", b =>
                {
                    b.HasOne("LoDb.Infrastructure.Persistence.PublicApi.ApiKey", "ApiKey")
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f47e0aa08be312b3");

                    b.Navigation("ApiKey");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("LoDb.Infrastructure.Persistence.Accounts.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_user_roles_identity_roles_role_id");

                    b.HasOne("LoDb.Infrastructure.Persistence.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("LoDb.Infrastructure.Persistence.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_user_tokens_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
