// <auto-generated />
using System;
using LoDb.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoDb.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LoDbDbContext))]
    [Migration("20260719150001_Baseline")]
    partial class Baseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Accounts.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BanReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ban_reason")
                        .HasDefaultValueSql("NULL");

                    b.Property<DateTimeOffset?>("BannedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("banned_at")
                        .HasDefaultValueSql("NULL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("email");

                    b.Property<string>("FavoriteChampionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("favorite_champion_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("FavoriteItemId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("favorite_item_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("FavoriteRuneId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("favorite_rune_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("FavoriteSkinId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("favorite_skin_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("FavoriteSummonerId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("favorite_summoner_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("google_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_banned");

                    b.Property<bool>("IsPublicProfile")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_public_profile");

                    b.Property<bool>("IsSupporter")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_supporter");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("PreferredVersion")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("preferred_version")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("RiotTagline")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("riot_tagline")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("roles");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("uniq_1483a5e976f5c865");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Billing.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountCents")
                        .HasColumnType("integer")
                        .HasColumnName("amount_cents");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("StripeSessionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_session_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("donations_pkey");

                    b.HasIndex("StripeSessionId")
                        .IsUnique()
                        .HasDatabaseName("uniq_cde989621a314a57");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_cde98962a76ed395");

                    b.ToTable("donations", (string)null);
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Builds.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChampionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("champion_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("sr")
                        .HasColumnName("game_mode");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("game_version");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_public");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("en_US")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("Runes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("runes");

                    b.Property<string>("ShareToken")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("share_token");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("steps");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("builds_pkey");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("idx_ab264a57e3c61f9");

                    b.HasIndex("ShareToken")
                        .IsUnique()
                        .HasDatabaseName("uniq_ab264a5d6594dd6");

                    b.ToTable("builds", (string)null);
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Builds.BuildVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildId")
                        .HasColumnType("integer")
                        .HasColumnName("build_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("Value")
                        .HasColumnType("smallint")
                        .HasColumnName("value");

                    b.Property<int>("VoterId")
                        .HasColumnType("integer")
                        .HasColumnName("voter_id");

                    b.HasKey("Id")
                        .HasName("build_votes_pkey");

                    b.HasIndex("BuildId")
                        .HasDatabaseName("idx_11530dc417c13f8b");

                    b.HasIndex("VoterId")
                        .HasDatabaseName("idx_11530dc4ebb4b8ad");

                    b.HasIndex("BuildId", "VoterId")
                        .IsUnique()
                        .HasDatabaseName("uniq_build_votes_build_voter");

                    b.ToTable("build_votes", (string)null);
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Contact.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("handled_at")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("new")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("subject")
                        .HasDefaultValueSql("NULL");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("contact_messages_pkey");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_412782018b8e8428");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_412782017b00651c");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_41278201a76ed395");

                    b.ToTable("contact_messages", (string)null);
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.PublicApi.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreditsBalance")
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("credits_balance");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("key_prefix");

                    b.Property<int>("MonthlyQuota")
                        .HasColumnType("integer")
                        .HasDefaultValue(500)
                        .HasColumnName("monthly_quota");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("free")
                        .HasColumnName("plan");

                    b.Property<int>("RateLimitPerMin")
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("rate_limit_per_min");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("revoked_at")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stripe_customer_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stripe_subscription_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("api_keys_pkey");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("uniq_9579321f57bfb971");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_9579321fa76ed395");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.PublicApi.ApiUsage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ApiKeyId")
                        .HasColumnType("integer")
                        .HasColumnName("api_key_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<long>("Requests")
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("requests");

                    b.HasKey("Id")
                        .HasName("api_usage_pkey");

                    b.HasIndex("ApiKeyId")
                        .HasDatabaseName("idx_f47e0aa08be312b3");

                    b.HasIndex("ApiKeyId", "Day")
                        .IsUnique()
                        .HasDatabaseName("uniq_api_usage_key_day");

                    b.ToTable("api_usage", (string)null);
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Billing.Donation", b =>
                {
                    b.HasOne("LoDb.Infrastructure.Persistence.Accounts.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cde98962a76ed395");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Builds.Build", b =>
                {
                    b.HasOne("LoDb.Infrastructure.Persistence.Accounts.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ab264a57e3c61f9");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Builds.BuildVote", b =>
                {
                    b.HasOne("LoDb.Infrastructure.Persistence.Builds.Build", "Build")
                        .WithMany()
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_11530dc417c13f8b");

                    b.HasOne("LoDb.Infrastructure.Persistence.Accounts.User", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_11530dc4ebb4b8ad");

                    b.Navigation("Build");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.Contact.ContactMessage", b =>
                {
                    b.HasOne("LoDb.Infrastructure.Persistence.Accounts.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_41278201a76ed395");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.PublicApi.ApiKey", b =>
                {
                    b.HasOne("LoDb.Infrastructure.Persistence.Accounts.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_9579321fa76ed395");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoDb.Infrastructure.Persistence.PublicApi.ApiUsage", b =>
                {
                    b.HasOne("LoDb.Infrastructure.Persistence.PublicApi.ApiKey", "ApiKey")
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f47e0aa08be312b3");

                    b.Navigation("ApiKey");
                });
#pragma warning restore 612, 618
        }
    }
}
