namespace LoDb.Infrastructure.Persistence.Migrations;

/// <summary>
/// The raw SQL of the baseline: what Doctrine created and the new stack does not map, in
/// Doctrine's own words.
/// </summary>
public partial class Baseline
{
    private static readonly string[] LegacyStatements =
    [
        // Case-insensitive uniqueness of the e-mail and the username, the rule the login
        // relies on: functional indexes, which the model cannot express.
        "CREATE UNIQUE INDEX uniq_users_email_lower ON users (LOWER(email));",
        "CREATE UNIQUE INDEX uniq_users_username_lower ON users (LOWER(username));",

        // Password reset requests of the legacy stack (SymfonyCasts bundle); lot 4 uses
        // Identity tokens instead.
        """
        CREATE TABLE reset_password_request (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            selector VARCHAR(20) NOT NULL,
            hashed_token VARCHAR(100) NOT NULL,
            requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            user_id INT NOT NULL,
            PRIMARY KEY (id));
        """,
        "CREATE INDEX idx_7ce748aa76ed395 ON reset_password_request (user_id);",
        """
        ALTER TABLE reset_password_request ADD CONSTRAINT fk_7ce748aa76ed395
            FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE;
        """,

        // Queue of Symfony Messenger (doctrine transport, auto_setup=0: no trigger).
        """
        CREATE TABLE messenger_messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            body TEXT NOT NULL,
            headers TEXT NOT NULL,
            queue_name VARCHAR(190) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY (id));
        """,
        """
        CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750
            ON messenger_messages (queue_name, available_at, delivered_at, id);
        """,

        // Doctrine's own history, filled with the 11 legacy migrations: the legacy stack
        // finds nothing to replay on a database the baseline created.
        """
        CREATE TABLE doctrine_migration_versions (
            version VARCHAR(191) NOT NULL,
            executed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            execution_time INT DEFAULT NULL,
            PRIMARY KEY (version));
        """,
        """
        INSERT INTO doctrine_migration_versions (version, executed_at, execution_time)
        SELECT version, (now() AT TIME ZONE 'UTC')::timestamp(0), NULL
        FROM unnest(ARRAY[
            'DoctrineMigrations\Version20260717101320',
            'DoctrineMigrations\Version20260717131738',
            'DoctrineMigrations\Version20260717140649',
            'DoctrineMigrations\Version20260717150000',
            'DoctrineMigrations\Version20260717180000',
            'DoctrineMigrations\Version20260717200000',
            'DoctrineMigrations\Version20260717203909',
            'DoctrineMigrations\Version20260717214500',
            'DoctrineMigrations\Version20260719120000',
            'DoctrineMigrations\Version20260719140000',
            'DoctrineMigrations\Version20260719150000']) AS version;
        """,
    ];
}
