using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Migrations.Operations;
using Microsoft.EntityFrameworkCore.Migrations.Operations.Builders;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LoDb.Infrastructure.Persistence.Migrations;

/// <summary>
/// Lots 6, 7, 9 and 10: the idempotence of the Stripe webhooks (<c>stripe_event</c>), the
/// credit grants and their expiry (<c>api_credit_grants</c>), the analytics events
/// partitioned by day (<c>analytics_event</c>) and their daily aggregates
/// (<c>analytics_daily</c>), and the policy of the apps (<c>client_policy</c>).
/// </summary>
/// <remarks>
/// Additive: new tables only, which the legacy stack ignores; <c>api_keys.credits_balance</c>
/// stays the counter both stacks spend. Each positive balance becomes a grant dated from the
/// migration, so that it expires twelve months later. <c>analytics_event</c> is created in raw
/// SQL, EF having no partitioned table, and without partitions: the analytics zone creates
/// them ahead of time.
/// </remarks>
public partial class Lot6BillingAnalyticsApps : Migration
{
    private const string CreateAnalyticsEvent = """
        CREATE TABLE analytics_event (
            id bigint GENERATED BY DEFAULT AS IDENTITY,
            occurred_at timestamp with time zone NOT NULL,
            origin character varying(16) NOT NULL,
            route character varying(128) NOT NULL,
            path character varying(1024) NOT NULL,
            type character varying(32) NOT NULL,
            kind character varying(16) NOT NULL,
            entity character varying(128),
            status smallint NOT NULL,
            version character varying(32),
            lang character varying(16),
            locale character varying(16) NOT NULL,
            ip character varying(45),
            visitor character varying(64) NOT NULL,
            user_agent character varying(512),
            browser character varying(32) NOT NULL,
            os character varying(32) NOT NULL,
            device character varying(16) NOT NULL,
            is_bot boolean NOT NULL,
            referer_host character varying(255),
            referer_source character varying(16) NOT NULL,
            country character varying(2),
            country_name character varying(64),
            CONSTRAINT pk_analytics_event PRIMARY KEY (occurred_at, id),
            CONSTRAINT ck_analytics_event_origin CHECK (origin IN ('page', 'navigation'))
        ) PARTITION BY RANGE (occurred_at)
        """;

    // Frozen here rather than read from the model: a migration never changes. The months are
    // counted in UTC, as DateTimeOffset.AddMonths does, whatever the session's time zone.
    private const string GrantBalances = """
        INSERT INTO api_credit_grants (api_key_id, source, requests, purchased_at, expires_at)
        SELECT id, 'migration', credits_balance, now(),
            (now() AT TIME ZONE 'UTC' + interval '12 months') AT TIME ZONE 'UTC'
        FROM api_keys
        WHERE credits_balance > 0
        ORDER BY id
        """;

    private const string ReleaseNumber = "'^[0-9]+\\.[0-9]+\\.[0-9]+$'";

    protected override void Up(MigrationBuilder migrationBuilder)
    {
        CreateStripeEvent(migrationBuilder);
        CreateApiCreditGrants(migrationBuilder);
        migrationBuilder.Sql(GrantBalances);
        migrationBuilder.Sql(CreateAnalyticsEvent);
        CreateAnalyticsDaily(migrationBuilder);
        CreateClientPolicy(migrationBuilder);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(name: "client_policy");
        migrationBuilder.DropTable(name: "analytics_daily");
        // Its partitions go with it.
        migrationBuilder.DropTable(name: "analytics_event");
        migrationBuilder.DropTable(name: "api_credit_grants");
        migrationBuilder.DropTable(name: "stripe_event");
    }

    private static void CreateStripeEvent(MigrationBuilder migrationBuilder) =>
        migrationBuilder.CreateTable(
            name: "stripe_event",
            columns: table => new
            {
                id = Varchar(table, 255, nullable: false),
                type = Varchar(table, 128, nullable: false),
                status = Varchar(table, 16, nullable: false),
                created_at = Timestamp(table, nullable: false),
                processed_at = Timestamp(table, nullable: false),
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_stripe_event", x => x.id);
                table.CheckConstraint(
                    "ck_stripe_event_status",
                    "status IN ('processed', 'ignored')");
            });

    private static void CreateApiCreditGrants(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "api_credit_grants",
            columns: table => new
            {
                id = Identity<long>(table, "bigint"),
                api_key_id = table.Column<int>(type: "integer", nullable: false),
                source = Varchar(table, 16, nullable: false),
                requests = table.Column<long>(type: "bigint", nullable: false),
                purchased_at = Timestamp(table, nullable: false),
                expires_at = Timestamp(table, nullable: false),
                stripe_session_id = Varchar(table, 255, nullable: true),
                expired_at = Timestamp(table, nullable: true),
                expired_requests = table.Column<long>(type: "bigint", nullable: true),
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_api_credit_grants", x => x.id);
                ConstrainApiCreditGrants(table);
                table.ForeignKey(
                    name: "fk_api_credit_grants_api_keys_api_key_id",
                    column: x => x.api_key_id,
                    principalTable: "api_keys",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });
        IndexApiCreditGrants(migrationBuilder);
    }

    private static void ConstrainApiCreditGrants<T>(CreateTableBuilder<T> table)
    {
        table.CheckConstraint(
            "ck_api_credit_grants_expired",
            "(expired_at IS NULL AND expired_requests IS NULL)"
            + " OR (expired_at IS NOT NULL AND expired_requests BETWEEN 0 AND requests)");
        table.CheckConstraint("ck_api_credit_grants_expires_at", "expires_at > purchased_at");
        table.CheckConstraint("ck_api_credit_grants_requests", "requests > 0");
        table.CheckConstraint(
            "ck_api_credit_grants_session",
            "(source = 'purchase') = (stripe_session_id IS NOT NULL)");
        table.CheckConstraint(
            "ck_api_credit_grants_source",
            "source IN ('purchase', 'migration', 'reconciliation', 'admin')");
    }

    private static void IndexApiCreditGrants(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateIndex(
            name: "ix_api_credit_grants_api_key_id_purchased_at",
            table: "api_credit_grants",
            columns: ["api_key_id", "purchased_at"]);
        migrationBuilder.CreateIndex(
            name: "ix_api_credit_grants_due",
            table: "api_credit_grants",
            column: "expires_at",
            filter: "expired_at IS NULL");
        migrationBuilder.CreateIndex(
            name: "ix_api_credit_grants_stripe_session_id",
            table: "api_credit_grants",
            column: "stripe_session_id",
            unique: true);
    }

    private static void CreateAnalyticsDaily(MigrationBuilder migrationBuilder) =>
        migrationBuilder.CreateTable(
            name: "analytics_daily",
            columns: table => new
            {
                day = table.Column<DateOnly>(type: "date", nullable: false),
                source = Varchar(table, 16, nullable: false),
                totals = table.Column<string>(type: "jsonb", nullable: false),
                buckets = table.Column<string>(type: "jsonb", nullable: false),
                visitors = table.Column<string>(type: "jsonb", nullable: false),
                country_names = table.Column<string>(type: "jsonb", nullable: false),
                updated_at = Timestamp(table, nullable: false),
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_analytics_daily", x => x.day);
                table.CheckConstraint(
                    "ck_analytics_daily_shape",
                    "jsonb_typeof(totals) = 'object' AND jsonb_typeof(buckets) = 'object'"
                    + " AND jsonb_typeof(visitors) = 'array'"
                    + " AND jsonb_typeof(country_names) = 'object'");
                table.CheckConstraint(
                    "ck_analytics_daily_source",
                    "source IN ('events', 'import')");
            });

    private static void CreateClientPolicy(MigrationBuilder migrationBuilder) =>
        migrationBuilder.CreateTable(
            name: "client_policy",
            columns: table => new
            {
                platform = Varchar(table, 16, nullable: false),
                minimum_version = Varchar(table, 32, nullable: true),
                latest_version = Varchar(table, 32, nullable: true),
                bundle_id = Varchar(table, 64, nullable: true),
                bundle_url = Varchar(table, 2048, nullable: true),
                bundle_checksum = Varchar(table, 64, nullable: true),
                bundle_signature = Varchar(table, 1024, nullable: true),
                bundle_minimum_native_version = Varchar(table, 32, nullable: true),
                published_at = Timestamp(table, nullable: false),
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_client_policy", x => x.platform);
                ConstrainClientPolicy(table);
            });

    private static void ConstrainClientPolicy<T>(CreateTableBuilder<T> table)
    {
        table.CheckConstraint(
            "ck_client_policy_bundle",
            "num_nonnulls(bundle_id, bundle_url, bundle_checksum, bundle_signature,"
            + " bundle_minimum_native_version) IN (0, 5)");
        table.CheckConstraint(
            "ck_client_policy_bundle_checksum",
            "bundle_checksum ~ '^[0-9a-f]{64}$'");
        table.CheckConstraint(
            "ck_client_policy_bundle_platform",
            "platform = 'android' OR bundle_id IS NULL");
        table.CheckConstraint(
            "ck_client_policy_platform",
            "platform IN ('desktop', 'android')");
        table.CheckConstraint(
            "ck_client_policy_versions",
            $"minimum_version ~ {ReleaseNumber} AND latest_version ~ {ReleaseNumber}"
            + $" AND bundle_minimum_native_version ~ {ReleaseNumber}");
    }

    private static OperationBuilder<AddColumnOperation> Identity<T>(
        ColumnsBuilder table,
        string type) =>
        table.Column<T>(type: type, nullable: false).Annotation(
            "Npgsql:ValueGenerationStrategy",
            NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

    private static OperationBuilder<AddColumnOperation> Varchar(
        ColumnsBuilder table,
        int maxLength,
        bool nullable) =>
        table.Column<string>(
            type: $"character varying({maxLength})",
            maxLength: maxLength,
            nullable: nullable);

    private static OperationBuilder<AddColumnOperation> Timestamp(
        ColumnsBuilder table,
        bool nullable) =>
        table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: nullable);
}
