// @ts-check
import eslint from '@eslint/js';
import angular from 'angular-eslint';
import { defineConfig, globalIgnores } from 'eslint/config';
import path from 'node:path';
import tseslint from 'typescript-eslint';
import { lodbPlugin } from './lint/lodb-plugin.mjs';

// Absolute, so the feature rule gives the same verdict whatever directory ESLint starts from.
const APP_ROOT = path.join(import.meta.dirname, 'src', 'app');

export default defineConfig([
  // The OpenAPI client is generated by L2.2 and never edited by hand.
  globalIgnores([
    'dist/**',
    'out-tsc/**',
    'coverage/**',
    '.angular/**',
    'src/app/core/api/generated/**',
  ]),
  {
    files: ['**/*.ts'],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommended,
      tseslint.configs.stylistic,
      angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    plugins: { lodb: lodbPlugin },
    rules: {
      '@angular-eslint/component-selector': [
        'error',
        { type: 'element', prefix: 'lodb', style: 'kebab-case' },
      ],
      '@angular-eslint/directive-selector': [
        'error',
        { type: 'attribute', prefix: 'lodb', style: 'camelCase' },
      ],
      '@angular-eslint/use-lifecycle-interface': 'error',
      '@typescript-eslint/consistent-type-definitions': ['error', 'interface'],
      // A leading underscore marks a parameter a signature imposes, such as Express's `next`.
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      // Size limits of the code rules (plan-implementation.md §4), enforced rather than reviewed.
      'max-lines': ['error', 400],
      'max-lines-per-function': ['error', { max: 30, skipBlankLines: true, skipComments: true }],
      'max-params': ['error', 3],
      'max-depth': ['error', 3],
      complexity: ['error', 10],
    },
  },
  {
    files: ['src/**/*.ts'],
    ignores: ['src/app/core/platform/**'],
    rules: { 'lodb/native-plugin-imports': 'error' },
  },
  {
    files: ['src/app/features/**/*.ts'],
    rules: { 'lodb/feature-boundaries': ['error', { appRoot: APP_ROOT }] },
  },
  {
    // A describe block groups every case of a unit: its length says nothing about complexity.
    files: ['**/*.spec.ts'],
    rules: { 'max-lines-per-function': 'off' },
  },
  {
    files: ['**/*.html'],
    extends: [angular.configs.templateRecommended, angular.configs.templateAccessibility],
  },
]);
