/** Every key the champion facets are labelled with, translated together by the list page. */
export const FACET_LABEL_KEYS = [
  'facet.group.profile',
  'facet.group.ratings',
  'facet.group.base_stats',
  'facet.champion.role',
  'facet.champion.roles.fighter',
  'facet.champion.roles.tank',
  'facet.champion.roles.mage',
  'facet.champion.roles.assassin',
  'facet.champion.roles.marksman',
  'facet.champion.roles.support',
  'facet.champion.resource',
  'facet.champion.resource_none',
  'facet.champion.range',
  'facet.champion.ranges.melee',
  'facet.champion.ranges.ranged',
  'facet.champion.difficulty',
  'facet.champion.attack',
  'facet.champion.defense',
  'facet.champion.magic',
  'stat.health',
  'stat.armor',
  'stat.magic_resist',
  'stat.attack_damage',
  'stat.attack_speed',
  'stat.move_speed',
];
