<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260717180000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Community lot: build votes (one per build/voter, cascade both sides), persisted donations '
            . '(unique Stripe session id = idempotency key, donor severable via SET NULL) and the supporter flag on users.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE build_votes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value SMALLINT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, build_id INT NOT NULL, voter_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_11530DC417C13F8B ON build_votes (build_id)');
        $this->addSql('CREATE INDEX IDX_11530DC4EBB4B8AD ON build_votes (voter_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_build_votes_build_voter ON build_votes (build_id, voter_id)');
        $this->addSql('CREATE TABLE donations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stripe_session_id VARCHAR(255) NOT NULL, amount_cents INT NOT NULL, currency VARCHAR(3) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CDE989621A314A57 ON donations (stripe_session_id)');
        $this->addSql('CREATE INDEX IDX_CDE98962A76ED395 ON donations (user_id)');
        $this->addSql('ALTER TABLE build_votes ADD CONSTRAINT FK_11530DC417C13F8B FOREIGN KEY (build_id) REFERENCES builds (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE build_votes ADD CONSTRAINT FK_11530DC4EBB4B8AD FOREIGN KEY (voter_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE donations ADD CONSTRAINT FK_CDE98962A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users ADD is_supporter BOOLEAN DEFAULT false NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE build_votes DROP CONSTRAINT FK_11530DC417C13F8B');
        $this->addSql('ALTER TABLE build_votes DROP CONSTRAINT FK_11530DC4EBB4B8AD');
        $this->addSql('ALTER TABLE donations DROP CONSTRAINT FK_CDE98962A76ED395');
        $this->addSql('DROP TABLE build_votes');
        $this->addSql('DROP TABLE donations');
        $this->addSql('ALTER TABLE users DROP is_supporter');
    }
}
