<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260717101320 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'User accounts + builds (PostgreSQL foundation), and the messenger doctrine transport table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE builds (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(80) NOT NULL, champion_id VARCHAR(64) NOT NULL, game_version VARCHAR(24) NOT NULL, description TEXT DEFAULT NULL, runes JSONB NOT NULL, steps JSONB NOT NULL, is_public BOOLEAN DEFAULT false NOT NULL, share_token VARCHAR(24) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AB264A5D6594DD6 ON builds (share_token)');
        $this->addSql('CREATE INDEX IDX_AB264A57E3C61F9 ON builds (owner_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, username VARCHAR(24) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_public_profile BOOLEAN DEFAULT false NOT NULL, favorite_champion_id VARCHAR(64) DEFAULT NULL, favorite_item_id VARCHAR(16) DEFAULT NULL, favorite_rune_id VARCHAR(16) DEFAULT NULL, favorite_summoner_id VARCHAR(64) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        // Case-insensitive uniqueness is the single source of truth for identity
        // lookups (login accepts email OR username, any casing). Functional
        // LOWER() indexes replace plain unique constraints on purpose; the ORM
        // mapping intentionally declares no column-level unique for these two.
        $this->addSql('CREATE UNIQUE INDEX uniq_users_email_lower ON users (LOWER(email))');
        $this->addSql('CREATE UNIQUE INDEX uniq_users_username_lower ON users (LOWER(username))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE builds ADD CONSTRAINT FK_AB264A57E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE builds DROP CONSTRAINT FK_AB264A57E3C61F9');
        $this->addSql('DROP TABLE builds');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
