<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Email confirmation + password reset: adds users.is_verified and the
 * reset_password_request table (SymfonyCasts bundle contract).
 */
final class Version20260717203909 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add users.is_verified and reset_password_request (email confirmation + password reset).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE reset_password_request (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              selector VARCHAR(20) NOT NULL,
              hashed_token VARCHAR(100) NOT NULL,
              requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              user_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              reset_password_request
            ADD
              CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql('ALTER TABLE users ADD is_verified BOOLEAN DEFAULT false NOT NULL');
        // Grandfather pre-existing accounts: they never received a confirmation
        // email, so treating them as verified avoids locking anyone out.
        $this->addSql('UPDATE users SET is_verified = true');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE reset_password_request DROP CONSTRAINT FK_7CE748AA76ED395');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('ALTER TABLE users DROP is_verified');
    }
}
