<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260717140649 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Paid public API: api_keys (hashed keys, plan/quota/credits + Stripe ids) and api_usage (daily metering written by go-api).';
    }

    public function up(Schema $schema): void
    {
        // Column names and the (api_key_id, day) unique index are a CONTRACT
        // with the go-api service (go-api/schema.sql): it SELECTs columns
        // nominatively and upserts api_usage with ON CONFLICT (api_key_id, day).
        $this->addSql('CREATE TABLE api_keys (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(64) NOT NULL, key_hash VARCHAR(64) NOT NULL, key_prefix VARCHAR(12) NOT NULL, plan VARCHAR(16) DEFAULT \'free\' NOT NULL, monthly_quota INT DEFAULT 500 NOT NULL, credits_balance BIGINT DEFAULT 0 NOT NULL, rate_limit_per_min INT DEFAULT 10 NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, stripe_customer_id VARCHAR(64) DEFAULT NULL, stripe_subscription_id VARCHAR(64) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9579321F57BFB971 ON api_keys (key_hash)');
        $this->addSql('CREATE INDEX IDX_9579321FA76ED395 ON api_keys (user_id)');
        $this->addSql('CREATE TABLE api_usage (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day DATE NOT NULL, requests BIGINT DEFAULT 0 NOT NULL, api_key_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F47E0AA08BE312B3 ON api_usage (api_key_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_api_usage_key_day ON api_usage (api_key_id, day)');
        $this->addSql('ALTER TABLE api_keys ADD CONSTRAINT FK_9579321FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE api_usage ADD CONSTRAINT FK_F47E0AA08BE312B3 FOREIGN KEY (api_key_id) REFERENCES api_keys (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE api_keys DROP CONSTRAINT FK_9579321FA76ED395');
        $this->addSql('ALTER TABLE api_usage DROP CONSTRAINT FK_F47E0AA08BE312B3');
        $this->addSql('DROP TABLE api_usage');
        $this->addSql('DROP TABLE api_keys');
    }
}
