<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Contact inbox: footer submissions (bug/feedback/review/sales) surfaced in
 * /admin and notified to the CONTACT_RECIPIENT mailbox. User data, so Postgres —
 * the account link is optional and severable (SET NULL) like donations.
 */
final class Version20260719140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add contact_messages (footer contact form submissions, admin inbox).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE contact_messages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(255) NOT NULL, name VARCHAR(120) DEFAULT NULL, email VARCHAR(255) NOT NULL, subject VARCHAR(160) DEFAULT NULL, message TEXT NOT NULL, locale VARCHAR(16) DEFAULT NULL, ip VARCHAR(64) DEFAULT NULL, status VARCHAR(255) DEFAULT \'new\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, handled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_41278201A76ED395 ON contact_messages (user_id)');
        $this->addSql('CREATE INDEX IDX_412782017B00651C ON contact_messages (status)');
        $this->addSql('CREATE INDEX IDX_412782018B8E8428 ON contact_messages (created_at)');
        $this->addSql('ALTER TABLE contact_messages ADD CONSTRAINT FK_41278201A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE contact_messages DROP CONSTRAINT FK_41278201A76ED395');
        $this->addSql('DROP TABLE contact_messages');
    }
}
