<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/LoDb.Ingestion/LoDb.Ingestion.csproj" />
    <ProjectReference Include="../LoDb.Testing/LoDb.Testing.csproj" />
  </ItemGroup>
</Project>
