using Microsoft.AspNetCore.Identity;

namespace LoDb.Infrastructure.Persistence.Accounts;

/// <summary>
/// A row of <c>users</c>, shared with the legacy stack until the cutover, and the Identity
/// user of the rewrite.
/// </summary>
/// <remarks>
/// <para>
/// Identity names map onto the legacy columns: <see cref="IdentityUser{TKey}.UserName"/> is
/// <c>username</c>, <see cref="IdentityUser{TKey}.PasswordHash"/> is <c>password</c> (bcrypt
/// or argon2, null for an account created through Google) and
/// <see cref="IdentityUser{TKey}.EmailConfirmed"/> is <c>is_verified</c>. The legacy stack
/// stores the e-mail lowercase; the e-mail and the username are unique whatever their case,
/// through the <c>LOWER()</c> indexes of the baseline.
/// </para>
/// <para>
/// The lot 4 columns are nullable or have a default, so the legacy stack keeps inserting
/// rows without knowing them. The normalized e-mail and username are generated by
/// PostgreSQL and never written; the phone number has no column.
/// </para>
/// </remarks>
public sealed class User : IdentityUser<int>
{
    /// <summary>Symfony roles, a JSON array such as <c>["ROLE_USER"]</c>, unused here.</summary>
    /// <remarks>Roles of the rewrite live in <c>identity_user_roles</c>.</remarks>
    public required IReadOnlyList<string> Roles { get; set; }

    public bool IsPublicProfile { get; set; }

    public string? FavoriteChampionId { get; set; }

    public string? FavoriteItemId { get; set; }

    public string? FavoriteRuneId { get; set; }

    public string? FavoriteSummonerId { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public string? GoogleId { get; set; }

    public string? RiotTagline { get; set; }

    public bool IsSupporter { get; set; }

    public bool IsBanned { get; set; }

    public DateTimeOffset? BannedAt { get; set; }

    public string? BanReason { get; set; }

    public string? FavoriteSkinId { get; set; }

    public string? PreferredVersion { get; set; }
}
