using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoDb.Infrastructure.Persistence.Accounts;

internal sealed class UserConfiguration : IEntityTypeConfiguration<User>
{
    private static readonly ValueConverter<IReadOnlyList<string>, string> RolesConverter = new(
        roles => JsonSerializer.Serialize(roles, (JsonSerializerOptions?)null),
        json => JsonSerializer.Deserialize<string[]>(json, (JsonSerializerOptions?)null)
            ?? Array.Empty<string>());

    private static readonly ValueComparer<IReadOnlyList<string>> RolesComparer = new(
        (left, right) => left!.SequenceEqual(right!),
        roles => roles.Aggregate(
            0,
            (hash, role) => HashCode.Combine(hash, StringComparer.Ordinal.GetHashCode(role))),
        roles => roles.ToArray());

    public void Configure(EntityTypeBuilder<User> builder)
    {
        builder.ToTable("users");
        builder.HasKey(user => user.Id).HasName("users_pkey");

        ConfigureLegacyColumns(builder);
        ConfigureIdentityColumns(builder);
        ConfigureNormalizedColumns(builder);

        builder.HasIndex(user => user.GoogleId)
            .IsUnique()
            .HasDatabaseName("uniq_1483a5e976f5c865");
    }

    // The Doctrine columns, sizes included: Identity's own mapping would widen the e-mail and
    // the username to 256 and break the comparison with the baseline.
    private static void ConfigureLegacyColumns(EntityTypeBuilder<User> builder)
    {
        builder.Property(user => user.Email).HasMaxLength(180).IsRequired();
        builder.Property(user => user.UserName)
            .HasColumnName("username")
            .HasMaxLength(24)
            .IsRequired();
        builder.Property(user => user.Roles)
            .HasColumnType("json")
            .HasConversion(RolesConverter, RolesComparer);
        builder.Property(user => user.PasswordHash).HasColumnName("password").HasMaxLength(255);
        builder.Property(user => user.IsPublicProfile).HasLegacyDefault(false);
        builder.Property(user => user.FavoriteChampionId).HasMaxLength(64).HasNullDefault();
        builder.Property(user => user.FavoriteItemId).HasMaxLength(16).HasNullDefault();
        builder.Property(user => user.FavoriteRuneId).HasMaxLength(16).HasNullDefault();
        builder.Property(user => user.FavoriteSummonerId).HasMaxLength(64).HasNullDefault();
        builder.Property(user => user.GoogleId).HasMaxLength(30).HasNullDefault();
        builder.Property(user => user.RiotTagline).HasMaxLength(5).HasNullDefault();
        builder.Property(user => user.IsSupporter).HasLegacyDefault(false);
        builder.Property(user => user.IsBanned).HasLegacyDefault(false);
        builder.Property(user => user.BannedAt).HasPrecision(0).HasNullDefault();
        builder.Property(user => user.BanReason).HasMaxLength(255).HasNullDefault();
        builder.Property(user => user.EmailConfirmed)
            .HasColumnName("is_verified")
            .HasLegacyDefault(false);
        builder.Property(user => user.FavoriteSkinId).HasMaxLength(64).HasNullDefault();
        builder.Property(user => user.PreferredVersion).HasMaxLength(24).HasNullDefault();
    }

    // Lot 4 columns. The legacy stack inserts rows without them: every one is nullable or has
    // a default, and lockout is on by default so that such an account is protected too.
    private static void ConfigureIdentityColumns(EntityTypeBuilder<User> builder)
    {
        builder.Property(user => user.SecurityStamp);
        builder.Property(user => user.ConcurrencyStamp).IsConcurrencyToken();
        builder.Property(user => user.LockoutEnd);
        builder.Property(user => user.LockoutEnabled).HasDefaultValue(true).ValueGeneratedNever();
        builder.Property(user => user.AccessFailedCount).HasDefaultValue(0).ValueGeneratedNever();
        builder.Property(user => user.TwoFactorEnabled)
            .HasDefaultValue(false)
            .ValueGeneratedNever();
        builder.Ignore(user => user.PhoneNumber);
        builder.Ignore(user => user.PhoneNumberConfirmed);
    }

    // Generated by PostgreSQL, so they stay right for rows the legacy stack writes. EF never
    // writes a computed column: the value UserManager sets is ignored, then read back.
    private static void ConfigureNormalizedColumns(EntityTypeBuilder<User> builder)
    {
        builder.Property(user => user.NormalizedEmail)
            .HasColumnName("normalized_email")
            .HasColumnType("text")
            .HasComputedColumnSql("upper((email)::text)", stored: true);
        builder.Property(user => user.NormalizedUserName)
            .HasColumnName("normalized_username")
            .HasColumnType("text")
            .HasComputedColumnSql("upper((username)::text)", stored: true);

        // Not unique: the baseline's LOWER() indexes already are, and an upper-case collision
        // of legacy rows must not fail the migration.
        builder.HasIndex(user => user.NormalizedEmail).HasDatabaseName("ix_users_normalized_email");
        builder.HasIndex(user => user.NormalizedUserName)
            .HasDatabaseName("ix_users_normalized_username");
    }
}
