import type { Translation } from '@jsverse/transloco';

/**
 * Catalogue entries the chrome and the primitives read, merged in by the gallery only: the
 * real catalogues arrive with L3.3. Taken from the legacy English and Arabic catalogues, so
 * the right-to-left check runs on real Arabic; the keys the Arabic catalogue lacks fall back
 * to English, as they do on the live site.
 */
export const GALLERY_STRINGS: Readonly<Record<'en' | 'ar', Translation>> = {
  en: {
    'api.nav.developers': 'API',
    'community.nav.trends': 'Trends',
    'detail.nav.back_to_list': 'Back to list',
    'detail.nav.label': 'Entity navigation',
    'detail.nav.next': 'Next',
    'detail.nav.previous': 'Previous',
    'detail.nav.sections': 'Page sections',
    'footer.contact.title': 'Contact',
    'footer.copyright': '© 2025 LINDECKER Charles / Hexanti',
    'footer.legal': 'Legal Notice',
    'footer.legal_title': 'Legal',
    'footer.links.title': 'Useful Links',
    'footer.navigation.title': 'Navigation',
    'footer.project.title': 'Project',
    'footer.project.updated': 'Updated: 17/07/2026',
    'footer.project.version': 'Version: {version}',
    'header.navigation.home': 'Home',
    'header.theme.close': 'Close',
    'header.theme.label': 'Visual theme',
    'nav.changelog': "What's new",
    'nav.codex': 'Encyclopedia',
    'nav.donate': 'Donate',
    'about.data.title': 'Data and sources',
    'about.faq.title': 'Frequently asked questions',
    'about.index.title': 'About League Of Data Base',
    'footer.contact.email': 'Email',
    'footer.contact.github': 'GitHub',
    'footer.contact.linkedin': 'LinkedIn',
    'footer.contact.repo': 'Source code',
    'footer.links.ddragon': 'CDN Data Dragon',
    'footer.links.lol': 'League of Legends',
    'footer.links.opgg': 'OP.GG',
    'footer.links.riotapi': 'Riot API',
    'footer.links.support': 'Riot Support',
    'footer.navigation.champion': 'Champion',
    'footer.navigation.home': 'Home',
    'footer.navigation.item': 'Item',
    'footer.navigation.runes': 'Runes',
    'footer.navigation.summoner': 'Summoner',
    'header.navigation.champion': 'Champions',
    'header.navigation.item': 'Items',
    'header.navigation.runes': 'Runes',
    'header.navigation.summoner': 'Summoner Spells',
    'legal.cookies.title': 'Cookie Policy',
    'legal.notice.title': 'Legal Notice',
    'legal.privacy.title': 'Privacy Policy',
    'legal.terms.title': 'Terms of Use',
    'nav.short.champions': 'Champions',
    'nav.short.home': 'Home',
    'nav.short.items': 'Items',
    'nav.short.runes': 'Runes',
    'nav.short.summoners': 'Spells',
  },
  ar: {
    'api.nav.developers': 'API',
    'community.nav.trends': 'الرائج',
    'footer.contact.title': 'تواصل',
    'footer.copyright': '© 2025 LINDECKER Charles / Hexanti',
    'footer.legal': 'إشعار قانوني',
    'footer.links.title': 'روابط مفيدة',
    'footer.navigation.title': 'التنقل',
    'footer.project.title': 'المشروع',
    'footer.project.updated': 'تحديث: 17/07/2026',
    'footer.project.version': 'الإصدار: {version}',
    'header.navigation.home': 'الرئيسية',
    'header.theme.close': 'إغلاق',
    'header.theme.label': 'المظهر المرئي',
    'about.data.title': 'البيانات والمصادر',
    'about.faq.title': 'الأسئلة الشائعة',
    'about.index.title': 'حول League Of Data Base',
    'footer.contact.email': 'البريد الإلكتروني',
    'footer.contact.github': 'GitHub',
    'footer.contact.linkedin': 'LinkedIn',
    'footer.links.ddragon': 'CDN Data Dragon',
    'footer.links.lol': 'League of Legends',
    'footer.links.opgg': 'OP.GG',
    'footer.links.riotapi': 'Riot API',
    'footer.links.support': 'Riot Support',
    'footer.navigation.champion': 'الأبطال',
    'footer.navigation.home': 'الرئيسية',
    'footer.navigation.item': 'العناصر',
    'footer.navigation.runes': 'الرونات',
    'footer.navigation.summoner': 'المستدعي',
    'header.navigation.champion': 'الأبطال',
    'header.navigation.item': 'العناصر',
    'header.navigation.runes': 'الرونات',
    'header.navigation.summoner': 'تعويذات المستدعي',
  },
};
